version: '3.8'

services:
  app:
    build: .
    env_file: 
      - service/DataBase.env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: P
      POSTGRES_USER: postgres  
      POSTGRES_DB: service_db
    env_file: 
      - service/DataBase.env
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: